"""add authorization_events table

Revision ID: 1faef166c05e
Revises: c995619b201b
Create Date: 2026-09-17 17:11:14.773318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1faef166c05e'
down_revision: Union[str, Sequence[str], None] = 'c995619b201b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_events_created_at'), 'authorization_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_authorization_events_tenant_id'), 'authorization_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_authorization_events_user_id'), 'authorization_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorization_events_user_id'), table_name='authorization_events')
    op.drop_index(op.f('ix_authorization_events_tenant_id'), table_name='authorization_events')
    op.drop_index(op.f('ix_authorization_events_created_at'), table_name='authorization_events')
    op.drop_table('authorization_events')
    # ### end Alembic commands ###
