"""add hash chain to authorization_events

Revision ID: 917c08fc19f5
Revises: 1faef166c05e
Create Date: 2026-09-17 17:18:03.904947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917c08fc19f5'
down_revision: Union[str, Sequence[str], None] = '1faef166c05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorization_events', sa.Column(
        'previous_hash', sa.String(length=64), nullable=False, server_default='GENESIS'))
    op.add_column('authorization_events', sa.Column(
        'self_hash', sa.String(length=64), nullable=False, server_default='UNHASHED'))
    # Backfill existing rows with placeholder hashes; the verify endpoint
    # will flag these until the backfill script runs (see Task 3).
    op.alter_column('authorization_events', 'previous_hash', server_default=None)
    op.alter_column('authorization_events', 'self_hash', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization_events', 'self_hash')
    op.drop_column('authorization_events', 'previous_hash')
    # ### end Alembic commands ###
