"""add event_id to attendance_events

Revision ID: fb1645089f9b
Revises: 4ff5ce93183a
Create Date: 2026-09-17 12:33:46.420873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1645089f9b'
down_revision: Union[str, Sequence[str], None] = '4ff5ce93183a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('event_id', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_attendance_event_id', 'attendance_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_event_id', 'attendance_events', type_='unique')
    op.drop_column('attendance_events', 'event_id')
    # ### end Alembic commands ###
