"""add team_id to users

Revision ID: fc33538a6a75
Revises: fb1645089f9b
Create Date: 2026-09-17 16:29:22.822722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc33538a6a75'
down_revision: Union[str, Sequence[str], None] = 'fb1645089f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###
